name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verify_files:
    name: Verify Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Lint Files
        run: npm run lint
      - name: Typecheck
        run: npm run typecheck

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test
